name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install package with test extras
        run: pip install -e ".[test]"

      - name: Run tests
        run: pytest
